version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python-packages:
      patterns:
        - "*"
  exclude-paths:
    - "requirements-py37.txt"
    - "uv.lock"
    - "requirements-dev.txt"
  cooldown:
    default-days: 30
