name: Generate release for youtube-local
run-name: ${{ github.actor }} is creating release for youtube-local
on:
  push:
    tags:
      - "*"

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Getting ubuntu version
        id: get-ubuntu-version
        run: |
          echo "DIST_CODENAME=$(lsb_release -c | awk '{print $2}')" >> "$GITHUB_ENV" 
          echo "WINEPREFIX=$HOME/winepython" >> "$GITHUB_ENV"
          echo "DISPLAY=:1" >> "$GITHUB_ENV"
      - name: Preparing packages
        id: packages-preparation
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo dd of=/etc/apt/keyrings/winehq-archive.key 
          wget -O - https://dl.winehq.org/wine-builds/ubuntu/dists/"$DIST_CODENAME"/winehq-"$DIST_CODENAME".sources | sudo dd of=/etc/apt/sources.list.d/winehq-"$DIST_CODENAME".sources
          sudo systemctl daemon-reload
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y --install-recommends winehq-devel p7zip p7zip-full xvfb
          echo "Wine and 7zip is installed"
      - name: Preparing repository
        id: repository-preparation
        uses: actions/checkout@v4
      - name: Generating release
        id: generating-release
        run: |
          cd ${{ github.workspace }}
          Xvfb :1 -screen 0 1024x768x24 &
          curl -LO "https://dl.winehq.org/wine/wine-mono/9.4.0/wine-mono-9.4.0-x86.msi"
          msiexec /i /q wine-mono-9.4.0-x86.msi
          curl -LO "https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe"
          wineconsole ./python-3.13.1-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 SimpleInstall=1 /nogui
          python3 ./generate_release.py 3.13.1
          rm -rf "$WINEPREFIX"
          curl -LO "https://www.python.org/ftp/python/3.8.10/python-3.8.10.exe"
          wineconsole ./python-3.8.10.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 SimpleInstall=1 /nogui
          python3 ./generate_release.py oldwin
          mkdir -p /tmp/output
          cp -v youtube-local*zip /tmp/output/
      - name: Uploading build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zip-package
          path: /tmp/output/
      - name: Creating youtube-local release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/output/*
