name: Generate release for youtube-local (oldwin)
run-name: ${{ github.actor }} is creating release for youtube-local
on:
  push:
    tags:
      - "*-pre"

jobs:
  generate-release:
    runs-on: windows-latest
    steps:
      - name: Preparing repository
        id: repository-preparation
        uses: actions/checkout@v4
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x86'
      - name: Generating release
        id: generating-release
        run: |
          choco install -y vcexpress2010
          cd ${{ github.workspace }}
          python ./generate_release.py oldwin
          mkdir -p output
          xcopy youtube-local*zip .\output\
      - name: Uploading build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zip-package
          path: ${{ github.workspace }}/output/
      - name: Creating youtube-local release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            ${{ github.workspace }}/output/*
